# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Joshua Loehr
tagline:          'A Software Developer'
description:      'A software developer with an affinity for all things data science, machine learning, & artificial intelligence.'
url:              https://joshualoehr.github.io
baseurl:          /

paginate:         5

# Custom vars
github:
  repo:           https://github.com/joshualoehr
