# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Josh
tagline:          'A Software Developer'
description:      'A description goes here.'
url:              https://joshualoehr.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/joshualoehr/joshualoehr.github.io
