# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Joshua Loehr
tagline:          'A Software Developer'
description:      'A software developer with an affinity for all things data science, machine learning, & artificial intelligence.'
url:              https://joshualoehr.github.io
baseurl:          /

paginate:         5

# Custom vars
github:
  repo:           https://github.com/joshualoehr
resume:
  current:        Joshua_Loehr_Resume_2021.pdf
  old1:        Joshua_Loehr_Resume_2021.pdf
  old2:           Joshua_Loehr_Resume_11-26-2018.pdf
  old3:           Joshua_Loehr_Resume_2018.pdf
